name: build
on:
  push:
    branches:
      - master
      - build-on-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: |
          FILES=$(git status --porcelain -- lib | wc -l)
          echo ::set-output name=updated::${FILES}
        id: files
      - run: echo "can you show this?"
        if: steps.files.outputs.updated != 0
      - run: |
          git config --local user.name $(git log -n1 --format="%an")
          git config --local user.email $(git log -n1 --format="%ae")
        if: steps.files.outputs.updated == 0
