name: build
on:
  push:
    - master
    - build-on-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: |
        FILES=$(git status --porcelain -- lib | wc -l)
        [ $FILES -eq 0 ] && exit 0
      - run: echo "can you show this?"
      - run: |
        git config --local user.name $(git log -n1 --format="%an")
        git config --local user.email $(git log -n1 --format="%ae")
